# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shahin
tagline:          'En promenad runt internet'
description:      'Pluggar <a href="http://www.urbandictionary.com/define.php?term=cash&20money&defid=250252">industriell ekonomi</a>. Allm&auml;nt intresserad av <a href="http://www.clankfp.org/files/titslapper/modermodemet.jpg">IT</a>. Lyssnar p&aring; <a href="http://open.spotify.com/artist/1gR0gsQYfi6joyO1dlp76N">Justice</a>. Jobbar p&aring; <a href="http://lurn.me">Lurn</a>. H&auml;rjar p&aring; <a href="http://sv.wikipedia.org/wiki/Internet">internet</a>.'
url:              http://wiwofone.github.io

author:
  name:           'Shahin Zarrabi'
  url:            https://twitter.com/wiwofone

paginate:         3