# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Shahin
tagline:          'En promenad runt internet'
description:      'Bloggar om IT och hur det p&aring;verkar och f&ouml;r&auml;ndrar samh&auml;llet dag f&ouml;r dag.'
url:              http://wiwofone.github.io

author:
  name:           'Shahin Zarrabi'
  url:            https://twitter.com/wiwofone

paginate:         1